### ISSUE TITLE
Please add dark mode support

### ISSUE THREAD

**Issue by phuchoa2001** [maciekt07/TodoApp#8]
I'd like to learn from your code implementation for dark mode. It would be a great learning experience for me.

**Comment by maciekt07** [comment]
Are you asking for dark mode support to be added to elements like the sidebar or menu?

**Comment by phuchoa2001** [comment]
Yes, I'd like that very much.

**Comment by maciekt07** [comment]
Sure I will try. Just keep in mind that I'm still learning so my code isn't perfect 😅
