### ISSUE TITLE
Lag issue

### ISSUE THREAD

**Issue by sigmaharsh** [maciekt07/TodoApp#9]
This  app is working well  absolutely but its somewhat laggy the response has a delay  
For example when clicking on settings and changing the theme the browser popped a message saying this app is slowing down the browser

**Comment by sigmaharsh** [comment]
I use Firefox to be more specific I'm using Linux as my primary os.
Keeping the issue aside I really appreciate your app dude it's awsome
Thanks for reaching out

**Comment by sigmaharsh** [comment]
I m on pretty old hardware maybe that would be primarily the case will close this issue

**Comment by maciekt07** [comment]
Glad to hear you're enjoying the app! Thanks for mentioning the lag. I've noticed some weird UI glitches on Firefox too, but i have no idea how to fix them at the moment
